### ISSUE TITLE
i get this error

### ISSUE THREAD

**Issue by WPHorhe** [tribalfs/GalaxyMaxHzPub#209]
PS C:\platform-tools> adb install --bypass-low-target-sdk-block "C:\Users\georg\Downloads\galaxy_max_hz_v8.1.apk"
Performing Streamed Install
adb: failed to install C:\Users\georg\Downloads\galaxy_max_hz_v8.1.apk:
Exception occurred while executing 'install':
java.lang.IllegalArgumentException: Unknown option --bypass-low-target-sdk-block
        at com.android.server.pm.PackageManagerShellCommand.makeInstallParams(PackageManagerShellCommand.java:2978)
        at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:1339)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:205)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCo

**Comment by tribalfs** [comment]
Only use this when installing on oneui6 or above. Otherwise, just install the apk normally.
